### ISSUE TITLE
Save as qml

### ISSUE THREAD

**Issue by NettaBen** [arc2qgis/lyrxtoqml#21]
@bogind 
This is the command to save as qml

            try:
                print(layer.name())
                layer.saveNamedStyle( layer.name() + ".qml")
            except Exception as e:
                print(e)

Thoughts: 
 - Checkbox save symbology to qml
- If the cb is checked, after repaint and 'Yay' msg - ask for location to save qml with layer.name()
yes - run command
- nay - no need :)

**Comment by bogind** [comment]
why not just add a file selection under the checkbox?
then we can add the save qml part to the run function and save the user from handling multiple messages.

**Comment by bogind** [comment]
added to new repo in https://github.com/arc2qgis/qlyrx/commit/1dd468f6145389c2b3019aa5e988463f952b5c7d
