### ISSUE TITLE
cant load any layer in plugins main dialog box (qgis 3.14.1)

### ISSUE THREAD

**Issue by krooven** [arc2qgis/lyrxtoqml#23]
The plugin doesn't recognize any vector layer form the canvas
Getting blank line instead.

**Comment by NettaBen** [comment]
Feel free to add more details
Qgis version
Did it work before
Is the curr canvas saved 
Etc

**Comment by bogind** [comment]
I thought it was an issue with an unsaved canvas too, but that doesn't seem to be the case.
Can you provide more details?
what layers did you have? 
from what sources?
are you sure they were seen as vector and not raster, mesh or vector tiles?
do you get any messages?
if you open the python console, are there any messages there?

**Comment by krooven** [comment]
A few more details
I used Qgis 3.14.1 (as mentioned in the title).
I tried many vector layers (just normal vector layers), with saved and non
saved canvas (project).
the plugin used to work in earlier versions of Qgis.

**Comment by bogind** [comment]
This seems to be an issue with QGIS 3.14.
Might have something to do with different handling of QGIS specific QT classes.
This version should do for now, will upload a proper version when i can get around to it.

[qlyrx.zip](https://github.com/arc2qgis/lyrxtoqml/files/5160189/qlyrx.zip)
