### ISSUE TITLE
Error Executing the plugin

### ISSUE THREAD

**Issue by danielraziel** [arc2qgis/lyrxtoqml#27]
Hi! When I try to apply a *.lyrx to a layer, I receive this error:

2024-06-05T19:04:13     WARNING    Traceback (most recent call last):
              File "C:\Users/User1/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qlyrx\qlyrx.py", line 1613, in run
              self.apply_lyrx_symbols(layer, self.j_data, geometry_general_type_str)
              File "C:\Users/User1/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qlyrx\qlyrx.py", line 1565, in apply_lyrx_symbols
              labels = self.parseLabels(label_symb_array, label_expessions, layer, rend_idx)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
              File "C:\Users/User1/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qlyrx\qlyrx.py", line 1144, in parseLabels
              label_settings.placement = 1
              ^^^^^^^^^^^^^^^^^^^^^^^^
             TypeError: a member of enum 'LabelPlacement' is expected not 'int'
             
2024-06-05T19:06:55     WARNING    Traceback (most recent call last):
              File "C:\Users/User1/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qlyrx\qlyrx.py", line 1611, in run
              geometry_general_type_str = self.generalise_geom_type(layer) if not isRaster else 'raster'
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
              File "C:\Users/User1/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qlyrx\qlyrx.py", line 386, in generalise_geom_type
              geometry_type_str = QgsWkbTypes.displayString(int(layer.wkbType()))
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
             TypeError: QgsWkbTypes.displayString(): argument 1 has unexpected type 'int'

**Comment by bogind** [comment]
Can you add your `*.lyrx` file and a sample dataset it should work on?

**Comment by danielraziel** [comment]
> Can you add your `*.lyrx` file and a sample dataset it should work on?

Sure! 
here are the files I wanted to use.

I wanted to use lyrx symbology for the field "NameKarbari"

[Landuse Samen.zip](https://github.com/user-attachments/files/15750385/Landuse.Samen.zip)

**Comment by bogind** [comment]
@danielraziel 
I just realized this discussion is in the wrong repository.
We moved everything to [https://github.com/arc2qgis/qlyrx](https://github.com/arc2qgis/qlyrx) a few **years** back.
What version of the plugin are you using and did you install it from the plugin manager?

**Comment by danielraziel** [comment]
> @danielraziel I just realized this discussion is in the wrong repository. We moved everything to https://github.com/arc2qgis/qlyrx a few **years** back. What version of the plugin are you using and did you install it from the plugin manager?

Thank you!
I'm using QGIS 3.36.2 and at first I installed it from github, and realized it has an update button, so I updated it via plugin manager which is 0.3.3
should I try the version without updating it?

**Comment by bogind** [comment]
@danielraziel 
There seems to have been an issue for QGIS versions above 3.30.
See [https://github.com/arc2qgis/qlyrx/issues/21#issue-2426986377](https://github.com/arc2qgis/qlyrx/issues/21#issue-2426986377)
I just uploaded version 0.3.4 to GitHub and QGIS Hub.
Until the new version is approved at QGIS Hub, you can install from the zip at [releases/v0.3.4](https://github.com/arc2qgis/qlyrx/releases/tag/v0.3.4)
